### ISSUE TITLE
遺言タイムの仕様相談

### ISSUE THREAD

**Issue by odagami** [sunheights208/sunjinro#16]
今だと以下の仕様
・1分間執行人と死ぬ人が喋っていいよ
・1分経ったらコマンド打って吊ってね
って感じ。

相談は
・時間過ぎたらどうする？
ってとこね

・自動で吊る
・しゃべれないだけで好きなタイミングで吊ってもらう

って案もあるんだがどうしようか

**Comment by ll560m** [comment]
あーねそれね
自動にしようか
