### ISSUE TITLE
執行人が居ない場合に進行不可になる

### ISSUE THREAD

**Issue by ll560m** [sunheights208/sunjinro#27]
残り3人（人狼、村人、占い師）のときに全員に1票ずつ入ると「執行人はundefinedさんです。」と表示され、遺言タイムには進むが1分経ってもミュートが外れたままで進行不可になる。

恐らく執行人が居ない状況を想定していないことから起こるバグ
この場合はまた全員で投票タイムを行い、票が3人に割れれば決選投票と同じように次のターンへ、票が一人に集まれば二人のうちから執行人を選出して処刑に進むのが良いと思う

**Comment by odagami** [comment]
めっちゃ良いパターン試したな。
明らかにバグ起きそうだもんな。

生存者全員が吊る対象となるパターンを想定してなかったのよね。

> この場合はまた全員で投票タイムを行い、票が3人に割れれば決選投票と同じように次のターンへ、票が一人に集まれば二人のうちから執行人を選出して処刑に進むのが良いと思う

このパターンで作ってみるわ

**Comment by odagami** [comment]
@ll560m 
以下簡単な動作確認で問題なし。
・同票
・吊られる人確定

**Comment by odagami** [comment]
OK

**Comment by odagami** [comment]
投票前に3人の会話を挟むようにする。

**Comment by odagami** [comment]
@ll560m 
話し合うように改修
