### ISSUE TITLE
決選投票の仕様が違う

### ISSUE THREAD

**Issue by ll560m** [sunheights208/sunjinro#28]
〇投票機能（票数が被ったらサドンデス→投票された二人が発言→""残った人たちだけで投票を行う""→それでも決まらなければ誰も死なずに夜のターンへ）
↑これ

つまり投票された側は決選投票に参加できないねん
例えばお砂とふみやの決選投票になったらその二人以外の人にしか投票権ないのよ

**Comment by odagami** [comment]
@ll560m 
被投票者にも投票権を与えるとゲームおかしくなっちゃう？
投票周りはバグ起きやすいから、必須でなければ初回はスルーしたいのよねん。

必須だったら実装するぞい。
