### ISSUE TITLE
[初期化]だけ入力したら全てのプレイヤーチャンネルを消す機能が欲しい

### ISSUE THREAD

**Issue by ll560m** [sunheights208/sunjinro#32]
完全にこれは俺が気になるからってだけなんだけど
管理者目線チャンネル多すぎてえげつないことになるからできればこの機能ほしい

簡単に実装できそうなら是非頼みたい
ちょっとだるいなら一旦いいわ

**Comment by odagami** [comment]
@ll560m 
割と簡単に実装できそうだから入れとくわね

**Comment by odagami** [comment]
@ll560m 
実装完了
「初期化」のみでユーザーチャンネルを全部消せる。
というか、以下のチャンネル以外を全部消すから他の残したいチャンネルがあったら実装せにゃならん。
heaven:
※jinro only※:
※in the game※:
village:
rule:
