### ISSUE TITLE
ゲーム中に個別チャットで初期化コマンドが通ってしまう/[廃村]コマンドの実装

### ISSUE THREAD

**Issue by ll560m** [sunheights208/sunjinro#33]
かいかい、kaikai、がみがみで村村狼
ゲーム開始後にかいかいの個別チャットで [初期化 kaikai 村人] と入力すると通ってしまった

普通にプレイしてたらありえない行動だけどこれは通っちゃダメかなと
初期化&開始コマンドは以下の仕様を追加した方が良いかもしれん
・#village でのみ有効
・ゲーム中は効かない

代わりに [廃村] コマンドを入力すると 「廃村にしますか？」 ってメッセージが出て多数決で廃村にするみたいな機能…はだるいか？
普通に #rule に「※[初期化]及び[開始]コマンドは絶対に勝手に使用しないでください」みたいな注意書きしとけばいいかな

どう思う？

**Comment by ll560m** [comment]
[廃村]機能、YESかNOしかなくてわかりやすいからリアクション(絵文字)使った投票機能の試作的な意味ではやってみていいかもってちょっと思ったり

**Comment by odagami** [comment]
> 解決策は３つやね
①[廃村]コマンドの実装（[初期化][開始]共にゲーム中は効かないようにする）
②[初期化][開始]コマンドをGMしか使えないようにする(discord側で「GM」みたいな役職作って付与された人だけが使えるような構造を作る)
③#rule に「※ゲーム中、[初期化]及び[開始]コマンドは勝手に使用しないでください」みたいな注意書きしとく(一番楽)

廃村機能ってどんなときに誰が使う想定してる？

今把握してる部分だけで思うに、廃村機能も前提の注意書きがなく、自由に使えたら意図しないことになりかねないのよね。
負けそうだから廃村にしよう！みたいな。コマンドの意図を伝えるのであれば、こんなことにはならないだろうけど、それなら③でも一緒だしなーって思う。
ただ、②の実装難易度は低いので②か①の２択かな。

だから廃村のユースケース（機能の使われる条件や状況）を詳しく聞いてから判断しようと思う。

**Comment by ll560m** [comment]
> 廃村機能ってどんなときに誰が使う想定してる？

設定ミス（よく考えてみたら人狼陣営不利すぎとか）とか参加者が急に増えた&減ったとかでゲームをリセットしたいときやね

> 今把握してる部分だけで思うに、廃村機能も前提の注意書きがなく、自由に使えたら意図しないことになりかねないのよね。

それは俺も思ったけど投票制にすることでまあ大丈夫かなっていう

> 負けそうだから廃村にしよう！みたいな。コマンドの意図を伝えるのであれば、こんなことにはならないだろうけど、それなら③でも一緒だしなーって思う。

俺が危惧してるのは「なんとなく出来心で[初期化][開始]打ってみたら通っちゃった」っていうやつなのよ
即反映だし回避できない
けど間に一個挟まるだけで違うと思うのよね

**Comment by ll560m** [comment]
まあでも[開始]押した人がGMってことになってそれ以外の人は＜進行コマンド＞使えないっていうのが一番綺麗で分かりやすいかもな

↑これなら俺らが居なくてもできるし
無いと思うけど

**Comment by odagami** [comment]
@ll560m 
おっけ。そしたら押した人をGM認定することにするわ。

**Comment by odagami** [comment]
@ll560m 
確認できないけど、以下の仕様にしてるからサーバー動き始めたら確認してちょ

初期化後
初期化：誰でも打てる
開始：誰でも打てる

ゲーム中
初期化：開始を打った人（GM）だけが打てる
開始：開始を打った人（GM）だけが打てる

ゲーム終了後
初期化：誰でも打てる
開始：誰でも打てる
